# Generated by Django 3.1.1 on 2020-10-16 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dingdan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuwuxiang', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='lifadian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shenfenzheng', models.CharField(max_length=18, unique=True)),
                ('dianzhuming', models.CharField(max_length=30)),
                ('dianzhulianxi', models.CharField(max_length=20, unique=True)),
                ('dianming', models.CharField(max_length=30)),
                ('dizhi', models.CharField(max_length=30)),
                ('mima', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='lifashi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shenfenzheng', models.CharField(max_length=18, null=True, unique=True)),
                ('xingming', models.CharField(max_length=30)),
                ('yonghuming', models.CharField(max_length=30)),
                ('mima', models.CharField(max_length=30)),
                ('lianxidianhua', models.CharField(max_length=30, unique=True)),
                ('xingbie', models.CharField(choices=[('1', '男'), ('0', '女')], max_length=1)),
                ('lifadian', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jianyue.lifadian')),
            ],
        ),
        migrations.CreateModel(
            name='yonghu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yonghuming', models.CharField(max_length=30)),
                ('mima', models.CharField(max_length=30)),
                ('xingming', models.CharField(max_length=30)),
                ('xingbie', models.CharField(choices=[('1', '男'), ('0', '女')], max_length=1)),
                ('lianxidianhua', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='jiesuandingdan',
            fields=[
                ('dingdan_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='jianyue.dingdan')),
                ('jieshushijian', models.DateTimeField()),
                ('shijifeiyong', models.FloatField()),
                ('shifouzhifu', models.BooleanField(default=0)),
            ],
            bases=('jianyue.dingdan',),
        ),
        migrations.CreateModel(
            name='yuyuedingdan',
            fields=[
                ('dingdan_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='jianyue.dingdan')),
                ('yuyuekaishi', models.DateTimeField()),
                ('yuyuexiaohao', models.TimeField()),
                ('gujifeiyong', models.FloatField()),
            ],
            bases=('jianyue.dingdan',),
        ),
        migrations.CreateModel(
            name='wuzi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wuziming', models.CharField(max_length=30)),
                ('wuzileixing', models.CharField(max_length=30)),
                ('shengyuliang', models.IntegerField()),
                ('shangcijinhuo', models.DateTimeField()),
                ('lifadianID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jianyue.lifadian')),
            ],
        ),
        migrations.CreateModel(
            name='renyuananpai',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anpaidingdan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jianyue.dingdan')),
                ('lifadian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jianyue.lifadian')),
                ('lifashi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jianyue.lifashi')),
            ],
        ),
        migrations.CreateModel(
            name='pingjia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pingfen', models.IntegerField()),
                ('pingjia', models.CharField(max_length=100)),
                ('dingdan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jianyue.dingdan')),
                ('yonghu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jianyue.yonghu')),
            ],
        ),
        migrations.CreateModel(
            name='lifashizhuang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zhuangtai', models.CharField(choices=[(1, '繁忙'), (0, '空闲')], max_length=1)),
                ('xiayikongxian', models.DateTimeField()),
                ('lifashi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jianyue.lifashi')),
            ],
        ),
        migrations.CreateModel(
            name='jixiaotongji',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuwuleixing', models.CharField(max_length=30)),
                ('zonghepingfen', models.FloatField()),
                ('lifadian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jianyue.lifadian')),
                ('lifashi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jianyue.lifashi')),
            ],
        ),
        migrations.AddField(
            model_name='dingdan',
            name='lifadian',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jianyue.lifadian'),
        ),
        migrations.AddField(
            model_name='dingdan',
            name='lifashi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jianyue.lifashi'),
        ),
        migrations.AddField(
            model_name='dingdan',
            name='yonghu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jianyue.yonghu'),
        ),
    ]
