# Generated by Django 3.1.1 on 2020-10-20 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jianyue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='fuwu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuwumingcheng', models.CharField(max_length=30)),
                ('leixing', models.CharField(choices=[('1', '洗吹'), ('2', '烫发'), ('3', '染发'), ('4', '剪发'), ('5', '护理')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='tupian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=500, unique=True)),
                ('lifadian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jianyue.lifadian')),
            ],
        ),
        migrations.CreateModel(
            name='lifashi_fuwu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuwu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jianyue.fuwu')),
                ('lifashi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jianyue.lifashi')),
            ],
        ),
        migrations.CreateModel(
            name='lifadian_fuwu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuwu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jianyue.fuwu')),
                ('lifadian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jianyue.lifadian')),
            ],
        ),
        migrations.CreateModel(
            name='faxing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tupian', models.CharField(max_length=30)),
                ('leixing', models.CharField(choices=[('1', '短发'), ('2', '烫发'), ('3', '长发'), ('4', '染发')], max_length=1)),
                ('beizhu', models.CharField(max_length=700)),
                ('lifashi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jianyue.lifashi')),
            ],
        ),
    ]
