# Generated by Django 3.1.1 on 2020-10-21 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jianyue', '0002_faxing_fuwu_lifadian_fuwu_lifashi_fuwu_tupian'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lifashi_fuwu',
            name='fuwu',
        ),
        migrations.RemoveField(
            model_name='lifashi_fuwu',
            name='lifashi',
        ),
        migrations.AddField(
            model_name='fuwu',
            name='jiage',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fuwu',
            name='lifashi',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='jianyue.lifashi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fuwu',
            name='pingjia',
            field=models.FloatField(default=5),
        ),
        migrations.AlterUniqueTogether(
            name='fuwu',
            unique_together={('fuwumingcheng', 'lifashi')},
        ),
        migrations.DeleteModel(
            name='lifadian_fuwu',
        ),
        migrations.DeleteModel(
            name='lifashi_fuwu',
        ),
    ]
