# Generated by Django 3.1.1 on 2020-10-26 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jianyue', '0004_auto_20201025_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wuzi',
            name='shengyuliang',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wuzi',
            name='wuzileixing',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='wuzi',
            name='wuziming',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='wuzi',
            unique_together=set(),
        ),
    ]
