# Generated by Django 3.1.1 on 2020-10-26 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jianyue', '0006_auto_20201026_1618'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wuzi',
            old_name='lifadianID',
            new_name='lifadian',
        ),
    ]
