# Generated by Django 3.1.1 on 2020-10-27 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jianyue', '0008_auto_20201026_2307'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wuzi',
            unique_together={('wuziming', 'wuzileixing', 'lifadian')},
        ),
        migrations.CreateModel(
            name='lifashiqitadizhi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lifadian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jianyue.lifadian')),
                ('lifashi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jianyue.lifashi')),
            ],
            options={
                'unique_together': {('lifadian', 'lifashi')},
            },
        ),
    ]
