# Generated by Django 3.1.1 on 2020-11-05 02:12

from django.db import migrations, models
import jianyue.models


class Migration(migrations.Migration):

    dependencies = [
        ('jianyue', '0015_auto_20201103_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='tupian',
            name='lujing',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='tupian',
            name='src',
            field=models.ImageField(upload_to=jianyue.models.upload_to),
        ),
    ]
