# Generated by Django 3.1.1 on 2020-11-08 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jianyue', '0019_auto_20201106_1814'),
    ]

    operations = [
        migrations.CreateModel(
            name='shoucang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beishoucang_id', models.CharField(max_length=700)),
                ('tupianleixing', models.CharField(choices=[('0', '理发店'), ('1', '理发师'), ('2', '服务')], max_length=1)),
                ('yonghu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jianyue.yonghu')),
            ],
            options={
                'unique_together': {('beishoucang_id', 'yonghu', 'tupianleixing')},
            },
        ),
    ]
