# Generated by Django 3.1.1 on 2020-11-08 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jianyue', '0020_shoucang'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yuyuedingdan',
            name='gujifeiyong',
        ),
        migrations.AddField(
            model_name='yuyuedingdan',
            name='yijieshou',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='yuyuedingdan',
            name='yuyuexiaohao',
            field=models.TimeField(null=True),
        ),
    ]
