# Generated by Django 3.1.1 on 2020-11-13 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jianyue', '0021_auto_20201108_2154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lifadian',
            name='dizhi',
        ),
        migrations.CreateModel(
            name='dizhi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lng', models.FloatField()),
                ('lat', models.FloatField()),
                ('lifadian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jianyue.lifadian')),
            ],
        ),
    ]
