# Generated by Django 3.1.1 on 2020-11-13 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jianyue', '0022_auto_20201113_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='dizhi',
            name='name',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
