# Generated by Django 3.1.1 on 2020-11-13 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jianyue', '0023_dizhi_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='dizhi',
            name='comprehension',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
